// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0grKHGCaPPIULaO4zTGzMKUG51l4kD24',
    appId: '1:1006357800871:web:a8000ecb27fa8c05f33882',
    messagingSenderId: '1006357800871',
    projectId: 'test-login-8d300',
    authDomain: 'test-login-8d300.firebaseapp.com',
    storageBucket: 'test-login-8d300.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXtptc2pxfh26M4cVoFExP3r5z4ntnLJM',
    appId: '1:1006357800871:android:206eea50e1fbb22ef33882',
    messagingSenderId: '1006357800871',
    projectId: 'test-login-8d300',
    storageBucket: 'test-login-8d300.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0grKHGCaPPIULaO4zTGzMKUG51l4kD24',
    appId: '1:1006357800871:web:7ca2b55f065e0922f33882',
    messagingSenderId: '1006357800871',
    projectId: 'test-login-8d300',
    authDomain: 'test-login-8d300.firebaseapp.com',
    storageBucket: 'test-login-8d300.firebasestorage.app',
  );

}